### ISSUE TITLE
Add support for pgettext

### ISSUE THREAD

**Issue by danigm** [Koka/gettext-rs#10]
pgettext is used to give context to translators:

https://www.gnu.org/software/gettext/manual/html_node/Contexts.html

I've been looking into the gettext code to view if I was able to add pgettext support to gettext-rs but I found that pgettext is a C macro so I think that's the reason for not having this in gettext-rs yet.

I'll continue reading about this, to try to have something working, if it's possible, but I'll leave this issue here, for other people to help, so I'll thanks any link or guide.

**Comment by Koka** [comment]
@danigm Thanks for your interest. I hope you'll be able to find more elegant solution, but I'm afraid that for now the only way to add support for those macros is to reimplement them in rust.
