### ISSUE TITLE
fatal error: getopt-pfx-core.h: No such file or directory

### ISSUE THREAD

**Issue by 0323pin** [Koka/gettext-rs#103]
OS: NetBSD-9.99.99
Rust: 1.62.1

Hi,
Trying to build `pika-backup` (https://gitlab.gnome.org/World/pika-backup/) which depends on `gettext-sys` yields the following error,

```
  --- localename.o ---
  In file included from /tmp/ted7-0/gettext/gettext-runtime/gnulib-lib/localename.c:33:
  ./locale.h:687:11: fatal error: setlocale_null.h: No such file or directory
    687 | # include "setlocale_null.h"
        |           ^~~~~~~~~~~~~~~~~~
  compilation terminated.
  *** [localename.o] Error code 1

  make[6]: stopped in /tmp/ted7-0/build/gettext-runtime/gnulib-lib
```

So, I've tried to build `gettext-rs` stand-alone within pkgsrc.
Only to hit the following error,

```
--- areadlink.o ---
  In file included from ./fcntl.h:79,
                   from /tmp/.tmpqVTOpD/gettext/gettext-runtime/gnulib-lib/careadlinkat.h:23,
                   from /tmp/.tmpqVTOpD/gettext/gettext-runtime/gnulib-lib/areadlink.c:27:
  ./unistd.h:637:11: fatal error: getopt-pfx-core.h: No such file or directory
    637 | # include <getopt-pfx-core.h>
        |           ^~~~~~~~~~~~~~~~~~~
  compilation terminated.
  --- binary-io.o ---
  In file included from ./fcntl.h:79,
                   from /tmp/.tmpqVTOpD/gettext/gettext-runtime/gnulib-lib/binary-io.h:22,
                   from /tmp/.tmpqVTOpD/gettext/gettext-runtime/gnulib-lib/binary-io.c:20:
  ./unistd.h:637:11: fatal error: getopt-pfx-core.h: No such file or directory
    637 | # include <getopt-pfx-core.h>
        |           ^~~~~~~~~~~~~~~~~~~
  compilation terminated.
```

Building it **outside** the tree using `cargo build --release` finishes successfully. But, the seems wrong.

Full build log: [build.txt](https://github.com/Koka/gettext-rs/files/9275378/build.txt)

Any hints?
Thanks!

**Comment by Minoru** [comment]
Sorry for the late reply! Both of those missing files are present in the tarball, so two possible causes are:

1. `tar` not entirely unpacking the archive;
2. the C compiler missing `-I` flags that lead to those files.

The first one seems unlikely as [we do check](https://github.com/Koka/gettext-rs/blob/ea91043635cfc44f442379d2b552166b7ec981a5/gettext-sys/build.rs#L291-L296) for the success there. It can be double-checked by pausing the process after it unpacked the files, and examining the temporary directory.

The second could be due to GNU gettext's ./configure script misdetecting the platform or something. I'd get the log from the successful build and compare it to the failing one, and see what's different -- that might give us more ideas.

Sorry I don't have a ready solution for you, but if you try these suggestions and tell me what you find, perhaps the situation will become clearer.

**Comment by 0-wiz-0** [comment]
I have tried to take a look at this. `gettext-rs` shows the log of the failed, but the paths are in `/tmp/.tmpsomething/build` and that directory does not exist after the build fails. Is there a way to tell the build to keep it so I can look there?

Btw, one possible reason for differences when building inside and outside pkgsrc is that pkgsrc hides some headers/libraries from the compiler if not explicitly told to allow them.

**Comment by Minoru** [comment]
Thanks for taking a look!

> Is there a way to tell the build to keep it so I can look there?

Not without modifying the crate: you can replace https://github.com/Koka/gettext-rs/blob/ea91043635cfc44f442379d2b552166b7ec981a5/gettext-sys/build.rs#L164-L165 with something like
```rust
let build_dir = {
  let build_dir = TempDir::new().unwrap(); 
  let path = build_dir.path();
  build_dir.leak(); // this is the important bit
  path
};
```

But I usually do it another way: I set up an environment where the problem happens, run a shell there, and manually execute all the commands that our build.rs runs. That gives me an opportunity to poke around the tree at various stages of the build.

> pkgsrc hides some headers/libraries from the compiler if not explicitly told to allow them.

In our case it looks like the compiler can't find the project's own headers; I find it hard to believe that pkgsrc would hide those, as it makes no sense to me. But again, I never used pkgsrc and might awfully misunderstand what's going on in there. You might try to disable that just in case, or allow it to access any headers and libraries.

**Comment by 0323pin** [comment]
I can build this now.
If I knew from start that it depends on systems `gettext-tools` to build, it would have save us all an headache 😄

**Comment by 0-wiz-0** [comment]
We could get it to build by setting:
```
GETTEXT_DIR=${PREFIX}
GETTEXT_SYSTEM=enabled
```
and making sure all parts of gettext were installed (pkgsrc splits the package into the library and the command line tools).
This ticket can be closed.

Thanks for the help!

**Comment by Minoru** [comment]
Sorry for the delayed response! Glad you figured it out.

@0323pin, do you mean that simply installing `gettext-tools` fixes the build? That's unexpected; if `GETTEXT_SYSTEM` is not enabled, the crate should be self-sufficient. Your statement seems to support my hypothesis about the include paths though: installing `gettext-tools` might have put getopt-pfx-core.h where the compiler could find it, fixing the build. I'll keep this issue open in case someone wants to investigate further.

@0-wiz-0, it's surprising to me that it needs gettext command-line tools. The library should be sufficient with `GETTEXT_SYSTEM=enabled`. What was the build error like if the library is present but the tools aren't?

**Comment by 0323pin** [comment]
@Minoru Not just by installing it but, by actually link it at compile time. Bellow the used lines on our package Makefile.

```
MAKE_ENV+=	GETTEXT_DIR=${PREFIX}
MAKE_ENV+=	GETTEXT_SYSTEM=enabled

TOOL_DEPENDS+=	gettext-tools>=0.19.4nb1:../../devel/gettext-tools
```

**Comment by Minoru** [comment]
@0323pin, ah, so you went the same route as @0-wiz-0. You can drop `GETTEXT_SYSTEM` then, as it doesn't apply in your case; see gettext-sys/build.rs.

Still weird that devel/gettext-lib is not enough. Could you dig the build errors from CI logs or something? pkgsrc.se doesn't list the contents of the built package, so I can't tell at a glance what stuff gettext-tools contains.

**Comment by Minoru** [comment]
I guess that's a "no" :)

**Comment by 0323pin** [comment]
> I guess that's a "no" :)

Sorry, it's not a no, it's simply because we have lost interest in `pika-backup`.
I can recreate the dummy package, what exactly would you like to get access to?
I'm rather busy the coming two weeks with real life stuff and might be hard to get it done before mid November but, I can try to get what you need, if I just understand exactly what.

**Comment by Minoru** [comment]
Ah, I see. What I'm curious about is: what errors do you get if you don't mention gettext-tools in `TOOL_DEPENDS`? I'm surprised that the tools are needed at all; a build log might help me understand if our build.rs accidentally depends on something it shouldn't depend on.

There's no hurry, I'm only curious, so please prioritize the real life stuff over this!

**Comment by 0323pin** [comment]
@Minoru Thanks! I'll get back to you with the logs when I find the time for it.

**Comment by 0323pin** [comment]
@Minoru Finally got some free time to run some tests.
Using the following Makefile to build a dummy-package,

```
# $NetBSD$

DISTNAME=	gettext-rs-0.7.0
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=Koka/}

MAINTAINER=	pkgsrc-users%NetBSD.org@localhost
HOMEPAGE=	https://github.com/Koka/gettext-rs/
COMMENT=	GNU Gettext FFI binding for Rust
LICENSE=	mit

.include "cargo-depends.mk"

USE_TOOLS+=	pkg-config
USE_LANGUAGES+=	c c++

#MAKE_ENV+=	GETTEXT_DIR=${PREFIX}
#MAKE_ENV+=	GETTEXT_SYSTEM=enabled

#TOOL_DEPENDS+=	gettext-tools>=0.19.4nb1:../../devel/gettext-tools

.include "../../lang/rust/cargo.mk"
.include "../../mk/bsd.pkg.mk"
```

Fails with https://pastebin.com/3uJqvkye

Uncommenting the line `MAKE_ENV+=	GETTEXT_DIR=${PREFIX}` fails with https://pastebin.com/jnnP7M3D

If I install `gettext-tools`
```
~ > please pkgin install gettext-tools
[please] password for pin:
reading local summary...
processing local summary...
calculating dependencies...done.

2 packages to install:
  gettext-tools-0.21nb3 gettext-lib-0.21

0 to refresh, 0 to upgrade, 2 to install
3978K to download, 11M to install

proceed ? [Y/n] y
gettext-lib-0.21.tgz                                      100%   62KB  62.0KB/s   00:01
gettext-tools-0.21nb3.tgz                                 100% 3916KB 783.3KB/s   00:05
installing gettext-tools-0.21nb3...
gettext-lib-0.21: copying /usr/pkg/share/examples/gettext/locale.alias to /usr/pkg/share/locale/locale.alias
gettext-tools-0.21nb3: registering info file /usr/pkg/info/gettext.info
gettext-tools-0.21nb3: registering info file /usr/pkg/info/libtextstyle.info
installing gettext-lib-0.21...
gettext-lib-0.21: copying /usr/pkg/share/examples/gettext/locale.alias to /usr/pkg/share/locale/locale.alias
pkg_install warnings: 0, errors: 0
reading local summary...
processing local summary...
marking gettext-tools-0.21nb3 as non auto-removable
```

And uncomment `TOOL_DEPENDS+=	gettext-tools>=0.19.4nb1:../../devel/gettext-tools`
Then it builds successfully.

Removing `gettext-tools` and having just `gettext-lib` installed fails with https://pastebin.com/VnNr2Jw3

You can find the contents of `gettext-lib` at the end of [this page](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/devel/gettext-lib/PLIST?rev=1.6&content-type=text/x-cvsweb-markup) and the contents of `gettext-tools` on [this one](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/devel/gettext-tools/PLIST?rev=1.15&content-type=text/x-cvsweb-markup).

Let me know if there's anything else I can do.

**Comment by Minoru** [comment]
Ah, I see: gettext-tools are needed in order to compile the systest crate. Apparently pkgsrc fetches the repo and builds everything that's in there. Mystery closed; thank you for the logs!
