### ISSUE TITLE
Support placeholders in strings

### ISSUE THREAD

**Issue by Cogitri** [Koka/gettext-rs#18]
Right now the `*gettext` functions only take one argument (which is the to be translated strings) and don't accept placeholders like `%s` , or `{name}`. This either leads to awkward translations like `format!("{} {}", gettext("Theme changed to"), theme)`, or to apps implementing their own wrappers, like so https://gitlab.gnome.org/GNOME/fractal/blob/ff7744efc07d91ffee3eecbe7f2598f9a1d9ec0b/fractal-gtk/src/i18n.rs#L46

**Comment by Cogitri** [comment]
So, is there something I can help with? How should we design this? Ideally we'd have something similar to how `format!` works (I guess we'll have to use a Macro, don't we?):

Should we honour what is between the curly braces, like:

`gettext!("Insert {number} of lines", number: <variable>)`

Or should they just be placeholders so the thing is easier to understand for translators, like:

`gettext!("Insert {number} of lines", <variable>)`

**Comment by Koka** [comment]
@Cogitri I really don't have enough experience using gettext to determine proper way to design this API. I'll be glad to accept any PR that properly addresses community's problem you've mentioned. For now I can see that macro approach you've described above looks promising.

**Comment by Minoru** [comment]
Hey, sorry for re-opening an old issue, but I'm trying to push gettext-rs into what I'd call a "completed" state and so far, the purpose of those macros elude me. Specifically, there are two problems with them:

1. **they break msgid extraction**. Tools like `msgextract` (from GNU gettext) and xtr (which targets Rust specifically) both analyze code to find the calls to gettext, and then extract the _string literal_ that is passed to the function. If you pass gettext a dynamic string, the extraction won't work, and so you'll have to write the .pot file yourself. This limits the usefulness of these macros;

2. **they do formatting before the translation**. Think of what this means for translators; in essence, they have to anticipate *all* possible results of formatting. In practice, this means that the only use for these macros is when we know the results in advance, and just want to save some typing by extracting a common part of the pattern into a format string, and looping over an array of options, formatting and translating each one. This further limits usefulness of the macros;

3. **they do not replace the code mentioned in the first comment of this issue**. Both `format!("{} {}", gettext("Theme changed to"), theme)` and https://gitlab.gnome.org/GNOME/fractal/blob/ff7744efc07d91ffee3eecbe7f2598f9a1d9ec0b/fractal-gtk/src/i18n.rs#L46 translate before the formatting.

Now, I do realize that `format!` requires a string literal for the format string, so we can't do `format!(gettext("…"), …)`. There are crates that provide this functionality ([strfmt](https://crates.io/crates/strfmt), [runtime-fmt](https://crates.io/crates/runtime-fmt), [dynfmt](https://crates.io/crates/dynfmt), possibly others), but there is no clear winner amongst them, and I don't think gettext-rs should depend on any of them.

@Cogitri, do you use those macros? Is my analysis of their limitations accurate? Would you agree that the macros as they are right now are very special-purpose, and should probably be taken out of gettext-rs?

**Comment by Cogitri** [comment]
Unfortunately the macros can't really be used anyway since GNU gettext's xgettext doesn't work with function names which have a `!` (like macros)

**Comment by Minoru** [comment]
[xtr](https://crates.io/crates/tr) supports that explicitly:

> xgettext cannot be told to extract string out of a macro, while xtr will ignore the ! token. So gettext(...) or gettext!(...) will work.

But IMHO our macros are still pretty useless: we would have something like `gettext!("Hello, {name}!", name = "Boris")`, xtr will extract "Hello, {name}!", but at runtime, this call will actually look up "Hello, Boris!". So it makes no sense to extract anything from our macros at all, which is one of my points above.

So, you agree that those macros can be removed? If they're of no use to *you*, the author, I'm pretty sure nobody else is using them either :)

**Comment by Cogitri** [comment]
> xtr supports that explicitly:

Yup, but at least the usecase I had in mind for the macros doesn't work until someone steps up and does the work in GNU Gettext (since GNOME's translation platform uses xgettext). Currently most GNOME applications copy and paste the same i18n utility functions from here: https://gitlab.gnome.org/GNOME/fractal/-/blob/master/fractal-gtk/src/util/i18n.rs. So it'd be nice if gettext-rs had something to actually use those functions properly.

> So, you agree that those macros can be removed? If they're of no use to you, the author, I'm pretty sure nobody else is using them either :)

IMHO we shouldn't remove them but fix them. The i18n functions above kind of suck because they take arrays instead of varargs but you can't really do varargs(-ish) without macros. So it'd be nice if gettext-rs just had ready to go macros which do the right thing.

**Comment by Minoru** [comment]
> the usecase I had in mind for the macros doesn't work until someone steps up and does the work in GNU Gettext 

These macros won't work even then. Even if `xgettext` is patched to understand macros, it will extract format strings (which are fed into `format!`), while `gettext()` will work on format**ted** strings (which are *results* of `format!`). There's no point in keeping the current macros around; they aren't, and will never become, useful.

> IMHO we shouldn't remove them but fix them.

I agree, but here's some context: the next gettext-rs release has to happen soon, since I recently fixed a rather serious flaw (#34). It's going to be a breaking release, because of #39 and #46. Therefore, it's a good opportunity to remove unused code like these macros.

I don't plan to work on new ones, but I do intend to keep this issue open, and hopefully one day we'll get a PR that implements this in a useable manner.

**Comment by Cogitri** [comment]
> There's no point in keeping the current macros around; they aren't, and will never become, useful.

They aren't useful in their current form, but they could become useful by doing runtime formatting similar to how the i18n functions in fractal work and would still be more comfortable than using arrays.
I can look into adjusting them to do that later today if that works for you.

**Comment by Minoru** [comment]
Yeah, I meant *this particular implementation is not useful*, not that the macros in general are useless. It'd be great if you can bring them into shape!
