### ISSUE TITLE
[request] Provide a quickstart guide for beginners

### ISSUE THREAD

**Issue by xliiv** [Koka/gettext-rs#25]
Let's say I have a program which I'd like to i18n.
What are the required steps to achieve that?
Usually working with `gettext` looks like this

> 1. prepare your program or module by specially marking translatable strings
> 2. run a suite of tools over your marked files to generate raw messages catalogs
> 3. create language-specific translations of the message catalogs
> 4. use the gettext module so that message strings are properly translated

from https://docs.python.org/3/library/gettext.html#internationalizing-your-programs-and-modules

Can you help me with this? If so, I could write the guide.

Thanks!

**Comment by Koka** [comment]
Some amount of information could be obtained from https://github.com/woboq/tr crate which provides some tooling built on top of gettext-rs (including xgettext replacement) and generic gettext guides like this https://phrase.com/blog/posts/learn-gettext-tools-internationalization/

Would be great to compile those into a single rust gettext manual
