### ISSUE TITLE
gettext-rs bindings unnecessarily entangle input types

### ISSUE THREAD

**Issue by Minoru** [Koka/gettext-rs#36]
Bindings provides by gettext-rs are polymorphic in that they'll accept anything that converts into a `Vec<u8>`:

https://github.com/Koka/gettext-rs/blob/ea171854d21e8c8b5a88d5738ad9e33524be247c/src/lib.rs#L78

However, in functions that take two or three strings, *all* strings are required to be of the same type:

https://github.com/Koka/gettext-rs/blob/ea171854d21e8c8b5a88d5738ad9e33524be247c/src/lib.rs#L87

https://github.com/Koka/gettext-rs/blob/ea171854d21e8c8b5a88d5738ad9e33524be247c/src/lib.rs#L114

This limitation forces users to convert all arguments to the same type before passing them to the functions, which I think diminishes the usefulness of polymorphism. We might've as well asked for `&[u8]` and left the user to perform the conversion.

I suggest we provide separate constraints for each polymorphic variable, letting the users supply whatever mix of types they want:

```rust
pub fn dngettext<T, U, V>(domain: T, singular: U, plural: V, n : u32) -> String
  where
    T: Into<Vec<u8>>,
    U: Into<Vec<u8>>,
    V: Into<Vec<u8>> { 
```

@Koka, I don't have any experience building libraries for others to use, so I'd like your input on this. Does my idea make sense at all? If it does, I'll send a pull request implementing this.

**Comment by Minoru** [comment]
Indeed, *our own code* could benefit from this. Here:

https://github.com/Koka/gettext-rs/blob/ea171854d21e8c8b5a88d5738ad9e33524be247c/src/text_domain.rs#L336-L338

the second argument is of type `PathBuf`, but we convert it into an `str` and then `String`, just to make the types match. This conversion is actually a bug, since it panics [if the path is not valid UTF-8](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.to_str).

**Comment by Koka** [comment]
Sounds good, we could also try to consume something like 'Into<String>' like described here https://hermanradtke.com/2015/05/06/creating-a-rust-function-that-accepts-string-or-str.html - for the first glance it looks very promising

**Comment by Minoru** [comment]
I think `Into<String>` is too constraining. Even though the GNU gettext manual [recommends](https://www.gnu.org/software/gettext/manual/gettext.html#Charset-conversion) for msgids to use ASCII, it's not a hard requirement — as far as I understand, gettext is happy to look up *any* byte sequence that doesn't have zeros in it. It's unlikely, but someone could come to depend on that, using e.g. ISO8859-15 encoding. If we constrain the interface to `Into<String>`, those users will be left out in the cold.

There is no ergonomics or performance advantage to `Into<String>`, so let's stick with the more general `Into<Vec<u8>>`.
