### ISSUE TITLE
gettext-rs wrappers for *textdomain* functions do not expose all of functionality

### ISSUE THREAD

**Issue by Minoru** [Koka/gettext-rs#44]
`bind_textdomain_codeset()`, `textdomain()`, and `bindtextdomain()` allow to pass in `NULL` to learn about the current domain and charset. Furthermore, they can report `ENOMEM` via `errno`. Our wrappers don't expose that, which is okay, but not great; we should do better.

**Comment by Minoru** [comment]
#48 exposes `errno`, so the only thing that remains to be exposed is the ability to query current settings by passing `NULL`.

I see three ways to implement this:

1. change arguments from `T` to `Option<T>`, closely modelling the C API, complicating callsites a bit;
2. provide separate getter functions, inventing our own interface;
3. change arguments from `T` to a special type that can be automatically constructed from either `T` or a sentry value that represents `NULL`. Something like this:

    ```rust
    // bindtextdomain() accepts a type that can be constructed from a `QUERY` constant,
    // which represents a NULL pointer passed to C API.
    let current_textdomain = bindtextdomain(gettextrs::QUERY);

    // The argument to bindtextdomain() can be transparently constructed from &str.
    bindtextdomain("hellorust");
    ```

    At a glance, this looks exactly like C API, but this would complicate the crate quite a bit, and I don't think the added complexity is worth it.

The first approach means that Rust API closely follows C API. This will certainly be appreciated by anyone who ports their code from C to Rust.

On the other hand, people new to gettext will be surprised to learn that a call like `bindtextdomain(None)` doesn't reset the text domain or anything like that — it's just a getter. We can document that, of course, but people rarely read docs :) So having a descriptively named function like `get_bound_textdomain()` could be nice.

I'm leaning towards the first approach. @Cogitri, you're using the library and know other users — do you have an opinion on this?

**Comment by Cogitri** [comment]
Perrsonally I'd rather have getter functions, while that might increase the porting effort a tiny bit for folks porting from C, I don't think it's significant and having getters makes the API a lot cleaner, I think.

**Comment by Minoru** [comment]
Okay, I'll add getters then. Probably in a separate module, so we don't have name collisions if GNU gettext adds similarly-named functions later on.

**Comment by Cogitri** [comment]
Yup, sounds like a good idea :+1:
