### ISSUE TITLE
TranslationNotFound("zh")

### ISSUE THREAD

**Issue by LJason77** [Koka/gettext-rs#60]
I have the code:
```rust
TextDomain::new("my_textdomain")
		.locale("zh_CN.UTF-8")
		.prepend(env::current_dir().unwrap().to_str().unwrap())
		.skip_system_data_paths()
		.init()
		.unwrap();
```

There are also my_textdomain.mo files in the project directory.

But get the error: TranslationNotFound("zh").

Did I do anything wrong?

What should I do?

**Comment by Minoru** [comment]
Hi! Where exactly is the my_texdomain.mo file? `TextDomain` would expect it at ./locale/zh\*/LC_MESSAGES/my_textdomain.mo (the asterisk means anything will match, including nothing at all, so it could be "zh", "zh-CN", "zh_CN", "zh whatever" etc.).

**Comment by LJason77** [comment]
Thank you for your reply.

I am using LC_IMAGES as LC_MESSAGES. How stupid I am.

Now everything is fine.

I'm sorry I wasted your time because of my stupidity.

**Comment by Minoru** [comment]
It's okay ;) Don't be so hard on yourself! I'm glad that the issue is resolved now ^_^
