### ISSUE TITLE
XDG_DATA_DIRS incorrect default if not specified

### ISSUE THREAD

**Issue by Hawk777** [Koka/gettext-rs#61]
According to [the XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
>  If `$XDG_DATA_DIRS` is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used.

However, `TextDomain::init` does not do that; instead, it uses `.` if `XDG_DATA_DIRS` is is unset and uses it as-is if it’s set but empty. I don’t imagine this will be a problem in practice very often, as I suspect most environments do set `XDG_DATA_DIRS`. Also, obviously those are not useful paths to search on a Windows machine, so I’m not sure whether it’s worth adding platform-specific logic, but I thought I would point out the fact that there is a default in the spec.

**Comment by Minoru** [comment]
Great catch, thank you! I submitted a PR that fixes it, and once CI checks are done, I'll release gettext-rs 0.7.0.
