### ISSUE TITLE
Can't build gettext-sys if any parent path has a space in it

### ISSUE THREAD

**Issue by audiodude** [Koka/gettext-rs#9]
Probably because of https://www.gnu.org/software/autoconf/manual/autoconf-2.60/autoconf.html#Special-Chars-in-Variables

I believe the solution would be to build gettext in /tmp or some other place that has a known good path, but I'm new to this project.

**Comment by audiodude** [comment]
Here's the output of running `$ cargo build` in gettext-sys from /tmp/space man/

$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling cc v1.0.18
   Compiling gettext-sys v0.19.8 (file:///private/tmp/space%20man/gettext-rs/gettext-sys)
error: failed to run custom build command for `gettext-sys v0.19.8 (file:///private/tmp/space%20man/gettext-rs/gettext-sys)`
process didn't exit successfully: `/private/tmp/space man/gettext-rs/target/debug/build/gettext-sys-80f993ee9d914c84/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_GETTEXT_SYSTEM
cargo:rerun-if-env-changed=GETTEXT_SYSTEM
cargo:rustc-link-lib=framework=CoreFoundation
cargo:rustc-link-lib=dylib=iconv
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_GETTEXT_DIR
cargo:rerun-if-env-changed=GETTEXT_DIR
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_GETTEXT_BIN_DIR
cargo:rerun-if-env-changed=GETTEXT_BIN_DIR
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_GETTEXT_LIB_DIR
cargo:rerun-if-env-changed=GETTEXT_LIB_DIR
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_GETTEXT_INCLUDE_DIR
cargo:rerun-if-env-changed=GETTEXT_INCLUDE_DIR
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "tar" "xJf" "/private/tmp/space man/gettext-rs/gettext-sys/gettext-0.19.8.1.tar.xz" "--strip-components" "1"
running: "sh" "/private/tmp/space man/gettext-rs/target/debug/build/gettext-sys-6fc3dea112695cd0/out/gettext/configure" "--without-emacs" "--disable-java" "--disable-csharp" "--disable-c++" "--disable-shared" "--enable-static" "--enable-fast-install" "--with-included-gettext" "--with-included-glib" "--with-included-libcroco" "--with-included-libunistring" "--prefix=/private/tmp/space man/gettext-rs/target/debug/build/gettext-sys-6fc3dea112695cd0/out"
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane...
--- stderr
configure: error: unsafe srcdir value: '/private/tmp/space man/gettext-rs/target/debug/build/gettext-sys-6fc3dea112695cd0/out/gettext'
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', gettext-sys/build.rs:251:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by Koka** [comment]
@audiodude Thanks for your feedback, I'll try to fix this when I'll have some spare time

**Comment by Minoru** [comment]
I reproduced with GNU gettext 0.21 on Debian testing. That's directly from the upstream's tarball, but with our `configure` options. I sent [an email to upstream](https://lists.gnu.org/archive/html/bug-gettext/2021-02/msg00007.html) to see if it's something they can fix; if not, I'll see if we can move the build to /tmp.

**Comment by Minoru** [comment]
[Got a reply](https://lists.gnu.org/archive/html/bug-gettext/2021-02/msg00008.html). This is indeed a limitation of autoconf, and not something upstream intends to address. GNU gettext maintainer also pointed out that it's dangerous to even *try* to build in such situation (since the commands can be cut short and do something unintended).

I'll work on moving the build to a temporary directory (don't know yet if I'll hard-code it, or rely on tempdir crate or something).
